export interface EnvironmentVariables {
  GCS_ARCHIVE_BUCKET_NAME: string;
  GOOGLE_APPLICATION_CREDENTIALS: string;
  PORT: string;
  PGBOSS_DATABASE: string;
  PGBOSS_APPLICATION_NAME: string;
  PGBOSS_USERNAME: string;
  PGBOSS_PASSWORD: string;
  PGBOSS_HOST: string;
  PGBOSS_PORT: string;
  STAMP_QUEUE_CHECK_INTERVAL_SECONDS?: string;
  STAMP_QUEUE_BATCH_SIZE: string;
  ARCHIVE_QUEUE_CHECK_INTERVAL_SECONDS?: string;
  ARCHIVE_QUEUE_CONCURRENCY: string;
  WEBHOOK_QUEUE_CHECK_INTERVAL_SECONDS?: string;
  WEBHOOK_QUEUE_CONCURRENCY: string;
  TASK_QUEUE_POLLING_ENABLED?: string;
}
